baseURL = "https://house-of-mint.github.io/hackers-hugo-blog/"

title = "Hackers [ˈhakɐs] Inn Blog"
author = "arrrrrmin"
theme = "hackers-inn"
languageCode = "en-us"
copyright = "2021 - [Hackers Inn e.V.](https://house-of-mint.org/)"

[params]
  excerpts = true
  description = "Hackers in blog. Projects and stories of a non commercial organization."

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/about"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
